//#define IDC_MI_AIR_FLOW               2005
//#define IDC_MI_AIR_FLOW_CAPTION       2006
#define IDS_MI_THROTTLE_GATE_TITLE      2007
#define IDC_MI_INDICATORS               2008
#define IDC_MI_TPS                      2009
#define IDC_MI_TACHOMETER               2010
#define IDC_MI_MAP                      2011
#define IDC_MI_VOLTMETER                2012
#define IDC_MI_DWELL_ANGLE              2013
#define IDC_MI_TEMPERATURE              2014
#define IDD_MEAS_INSTRUMENT_DESK        2015
#define IDD_RAW_SENSORS_DESK            2016
#define IDC_RS_MAP_VALUE                2017
#define IDC_RS_MAP_UNIT                 2018
#define IDC_RS_MAP_CAPTION              2019
#define IDC_RS_UBAT_VALUE               2020
#define IDC_RS_UBAT_CAPTION             2021
#define IDC_RS_UBAT_UNIT                2022
#define IDC_RS_TEMP_VALUE               2023
#define IDC_RS_TEMP_CAPTION             2024
#define IDC_RS_TEMP_UNIT                2025
#define IDC_RS_KNOCK_VALUE              2026
#define IDC_RS_KNOCK_CAPTION            2027
#define IDC_RS_KNOCK_UNIT               2028
#define IDS_MI_VOLTAGE_TITLE            2029
#define IDS_MI_VOLTAGE_UNIT             2030
#define IDS_MI_TEMPERATURE_TITLE        2031
#define IDS_MI_TEMPERATURE_UNIT         2032
#define IDS_MI_TACHOMETER_TITLE         2033
#define IDS_MI_TACHOMETER_UNIT          2034
#define IDS_MI_PRESSURE_TITLE           2035
#define IDS_MI_PRESSURE_UNIT            2036
#define IDS_MI_ADVANGLE_TITLE           2037
#define IDS_MI_ADVANGLE_UNIT            2038
#define IDD_DBGVAR_DESK                 2039
#define IDC_DV_VAR1_VALUE               2040
#define IDC_DV_VAR2_VALUE               2041
#define IDC_DV_VAR3_VALUE               2042
#define IDC_DV_VAR4_VALUE               2043
#define IDC_DV_VAR1_CAPTION             2044
#define IDC_DV_VAR2_CAPTION             2045
#define IDC_DV_VAR3_CAPTION             2046
#define IDC_DV_VAR4_CAPTION             2047
#define IDC_DV_BASE1_CHECK              2048
#define IDC_DV_BASE2_CHECK              2049
#define IDC_DV_BASE3_CHECK              2050
#define IDC_DV_BASE4_CHECK              2051
#define IDC_RS_TPS_VALUE                2052
#define IDC_RS_TPS_CAPTION              2053
#define IDC_RS_TPS_UNIT                 2054
#define IDC_RS_ADD_I1_VALUE             2055
#define IDC_RS_ADD_I1_CAPTION           2056
#define IDC_RS_ADD_I1_UNIT              2057
#define IDC_RS_ADD_I2_VALUE             2058
#define IDC_RS_ADD_I2_CAPTION           2059
#define IDC_RS_ADD_I2_UNIT              2060
#define IDD_CE_ERRORS_DESK              2061
#define IDC_CE_DESK_CE                  2062
#define IDC_CE_DESK_0                   2063
#define IDC_CE_DESK_1                   2064
#define IDC_CE_DESK_2                   2065
#define IDC_CE_DESK_3                   2066
#define IDC_CE_DESK_4                   2067
#define IDC_CE_DESK_5                   2068
#define IDC_CE_DESK_6                   2069
#define IDC_CE_DESK_7                   2070
#define IDC_CE_DESK_8                   2071
#define IDC_CE_DESK_9                   2072
#define IDC_CE_DESK_10                  2073
#define IDC_CE_DESK_11                  2074
#define IDC_CE_DESK_12                  2075
#define IDC_CE_DESK_13                  2076
#define IDC_CE_DESK_14                  2077
#define IDC_CE_DESK_15                  2078
#define IDS_CE_ERRORS_DESK_TT           2079
#define IDC_MI_ADD_I1                   2082
#define IDC_MI_ADD_I2                   2083
#define IDS_MI_ADD_I1_TITLE             2084
#define IDS_MI_ADD_I2_TITLE             2085
#define IDS_MI_ADD_I1_TT                2086
#define IDS_MI_ADD_I2_TT                2087
#define IDS_MI_KM                       2088
#define IDS_MI_KM_H                     2089
#define IDD_LOG_MARKS_DESK              2090
#define IDC_LOG_MARKS_K1                2091
#define IDC_LOG_MARKS_K2                2092
#define IDC_LOG_MARKS_K3                2093
#define IDS_LOG_MARKS_DESK_TT           2094
#define IDS_MI_TPS_FMT_STR              2095
#define IDC_MI_INJ_PW                   2096
#define IDS_MI_INJ_PW_TITLE             2097
#define IDS_MI_MS_UNIT                  2098
#define IDS_MI_IAT_TITLE                2099
#define IDC_MI_IAT                      2100
#define IDC_MI_EGO_CORR                 2101
#define IDS_MI_EGO_CORR_TITLE           2102
#define IDS_MI_PERCENT_UNIT             2103
#define IDS_CED_CKPS_MALFUNCTION_TT     2104
#define IDS_CED_EEPROM_PARAM_BROKEN_TT  2105
#define IDS_CED_PROGRAM_CODE_BROKEN_TT  2106
#define IDS_CED_KSP_CHIP_FAILED_TT      2107
#define IDS_CED_KNOCK_DETECTED_TT       2108
#define IDS_CED_MAP_SENSOR_FAIL_TT      2109
#define IDS_CED_TEMP_SENSOR_FAIL_TT     2110
#define IDS_CED_VOLT_SENSOR_FAIL_TT     2111
#define IDS_CED_DWELL_CONTROL_TT        2112
#define IDS_CED_CAMS_MALFUNCTION_TT     2113
#define IDS_CED_TPS_SENSOR_FAIL_TT      2114
#define IDS_CED_ADD_I1_SENSOR_TT        2115
#define IDS_CED_ADD_I2_SENSOR_TT        2116
#define IDS_CED_ADD_I3_SENSOR_TT        2117
#define IDS_CED_ADD_I4_SENSOR_TT        2118
#define IDS_CED_SYS_START_TT            2119
#define IDS_MI_MP_H                     2120
#define IDS_MI_MI                       2121
#define IDC_RS_ADD_I3_VALUE             2122
#define IDC_RS_ADD_I3_CAPTION           2123
#define IDC_RS_ADD_I3_UNIT              2124
#define IDC_RS_ADD_I4_VALUE             2125
#define IDC_RS_ADD_I4_CAPTION           2126
#define IDC_RS_ADD_I4_UNIT              2127
#define IDS_MI_IND_GAS_V                2128
#define IDS_MI_IND_CARB                 2129
#define IDS_MI_IND_IDLEVALVE            2130
#define IDS_MI_IND_POWERVALVE           2131
#define IDS_MI_IND_STBLOCK              2132
#define IDS_MI_IND_AE                   2133
#define IDS_MI_IND_COOLINGFAN           2134
