//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by secu3man.rc
//
#define IDD_ABOUTBOX                    4000
#define IDR_MAINFRAME                   4001
#define IDR_SECU3MTYPE                  4002
#define IDD_PARAMETERS_AND_MONITOR      4003
#define IDD_FIRMWARE_SUPPORT            4004
#define IDB_MAIN_TAB_CTRL_BITMAPS       4005
#define IDC_MAIN_TAB_CTRL               4006
#define IDC_FIRMWARE_SUPPORT_VIEW_START_MAP 4007
#define IDC_FIRMWARE_SUPPORT_FUNSET_LIST 4008
#define IDC_FIRMWARE_SUPPORT_VIEW_IDLE_MAP 4009
#define IDC_FIRMWARE_SUPPORT_VIEW_WORK_MAP 4010
#define IDC_FIRMWARE_SUPPORT_VIEW_TEMP_MAP 4011
#define IDC_CHECK1                      4012
#define IDC_FIRMWARE_SUPPORT_BL_STARTED_EMERGENCY 4012
#define IDC_PM_SHOW_RAW_SENSORS         4012
#define IDC_FIRMWARE_SUPPORT_FW_INFORMATION 4013
#define IDC_COMBO1                      4014
#define IDC_STATUS_INFO                 4015
#define IDC_APP_SETTINGS_BL_BAUDRATE_SELECTION_COMBO 4015
#define ID_APP_SETTINGS                 4016
#define IDC_APP_SETTINGS_PORT_SELECTION_COMBO 4016
#define IDS_STRING61204                 4017
#define IDD_APP_SETTINGS                4018
#define ID_MAIN_STATUS_BAR              4019
#define ID_MSB_INDICATOR_LOGO           4020
#define ID_MSB_INDICATOR_CONNTXT        4021
#define ID_MSB_INDICATOR_PROGRESS       4022
#define ID_MSB_INDICATOR_PERCENT        4023
#define ID_MSB_INDICATOR_ICON           4024
#define ID_MSB_INDICATOR_EMPTY          4025
#define IDM_READ_FLASH                  4026
#define IDM_WRITE_FLASH                 4027
#define IDM_READ_FLASH_TO_FILE          4028
#define IDM_WRITE_FLASH_FROM_FILE       4029
#define IDM_READ_EEPROM_TO_FILE         4030
#define IDM_WRITE_EEPROM_FROM_FILE      4031
#define IDS_READ_FLASH                  4032
#define IDS_WRITE_FLASH                 4033
#define IDS_READ_FLASH_TO_FILE          4034
#define IDS_WRITE_FLASH_FROM_FILE       4035
#define IDS_READ_EEPROM_TO_FILE         4036
#define IDS_WRITE_EEPROM_FROM_FILE      4037
#define IDM_OPEN_FLASH                  4038
#define IDM_SAVE_FLASH                  4039
#define IDS_OPEN_FLASH                  4040
#define IDS_SAVE_FLASH                  4041
#define IDS_READ_BOOTLOADER_SIGNATURE   4042
#define IDM_READ_BOOTLOADER_SIGNATURE   4043
#define IDS_CONN_CONNECTED              4044
#define IDS_CONN_DISCONNECTED           4045
#define IDS_CONN_BOOTLOADER             4046
#define IDS_IMPORT_FW_DATA_FROM_ANOTHER_FW 4047
#define IDM_IMPORT_FW_DATA_FROM_ANOTHER_FW 4048
#define IDS_IMPORT_FW_DATA_FROM_SECU3   4049
#define IDM_IMPORT_FW_DATA_FROM_SECU3   4050
#define IDI_CONN_CONNECTED              4051
#define IDI_CONN_DISCONNECTED           4052
#define IDI_CONN_BOOTLOADER             4053
#define IDC_APP_SETTINGS_APP_BAUDRATE_SELECTION_COMBO 4054
#define IDC_FIRMWARE_SUPPORT_FW_INFORMATION_LABEL 4055
#define IDC_FIRMWARE_SUPPORT_MAP_GROUPBOX 4056
#define IDC_FIRMWARE_SUPPORT_CRC        4057
#define IDC_FIRMWARE_SUPPORT_FW_NAME    4058
#define IDC_FIRMWARE_SUPPORT_MODIFICATION_FLAG 4059
#define IDC_FIRMWARE_SUPPORT_PROG_ONLY_CODE 4060


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4064
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         4300
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
