#define IDD_TD_BUTTONS_PANEL            5001
#define IDC_TD_VIEW_START_MAP           5002
#define IDC_TD_VIEW_IDLE_MAP            5003
#define IDC_TD_VIEW_WORK_MAP            5004
#define IDC_TD_VIEW_TEMP_MAP            5005
#define IDD_TD_ALLTABLES_PANEL          5006
#define IDC_TD_VIEW_DWELL_CONTROL       5007
#define IDC_TD_VIEW_ATTENUATOR_MAP      5008
#define IDC_TD_FUNSET_LIST              5009
#define IDC_TD_MAP_GROUPBOX             5010
#define IDS_MAPS_RPM_UNIT               5011
#define IDS_MAPS_ADVANGLE_UNIT          5012
#define IDS_START_MAP                   5013
#define IDS_IDLE_MAP                    5014
#define IDS_WORK_MAP                    5015
#define IDS_TEMPCORR_MAP                5016
#define IDS_MAPS_TEMPERATURE_UNIT       5017
#define IDS_MAPS_ATTENUATOR_GAIN_UNIT   5018
#define IDS_ATTENUATOR_MAP              5019
#define IDS_MAPS_VOLT_UNIT              5020
#define IDS_MAPS_DWELLCNTRL_UNIT        5021
#define IDS_DWELLCNTRL_MAP              5022
#define IDB_CALC_UP                     5023
#define IDB_CALC_DOWN                   5024
#define IDB_CALC_FOCUSED                5025
#define IDB_CALC_DISABLED               5026
#define IDC_TD_DWELL_CALC_BUTTON        5027
#define IDD_DWELL_CALC                  5028
#define IDC_DWELL_CALC_R_EDIT           5029
#define IDC_DWELL_CALC_R_SPIN           5030
#define IDC_DWELL_CALC_L_EDIT           5031
#define IDC_DWELL_CALC_L_SPIN           5032
#define IDC_DWELL_CALC_I_EDIT           5033
#define IDC_DWELL_CALC_I_SPIN           5034
#define IDC_TD_VIEW_CTS_CURVE           5035
#define IDS_CTS_CURVE_MAP               5036
#define IDS_TD_DWELL_CALC_BUTTON_TT     5037
#define IDS_TD_VIEW_DWELL_CONTROL_TT    5038
#define IDS_CHOKE_OP_UNIT               5040
#define IDS_CHOKE_OP_MAP                5041
#define IDD_RPM_GRID_EDITOR             5042
#define IDC_RGE_EDIT_0                  5043
#define IDC_RGE_EDIT_1                  5044
#define IDC_RGE_EDIT_2                  5045
#define IDC_RGE_EDIT_3                  5046
#define IDC_RGE_EDIT_4                  5047
#define IDC_RGE_EDIT_5                  5048
#define IDC_RGE_EDIT_6                  5049
#define IDC_RGE_EDIT_7                  5050
#define IDC_RGE_EDIT_8                  5051
#define IDC_RGE_EDIT_9                  5052
#define IDC_RGE_EDIT_10                 5053
#define IDC_RGE_EDIT_11                 5054
#define IDC_RGE_EDIT_12                 5055
#define IDC_RGE_EDIT_13                 5056
#define IDC_RGE_EDIT_14                 5057
#define IDC_RGE_EDIT_15                 5058
#define IDC_RGE_LOAD_DEF_VAL            5059
#define IDC_RGE_ERROR_MSG_TEXT          5060
#define IDB_GRID_UP                     5061
#define IDB_GRID_DOWN                   5062
#define IDB_GRID_FOCUSED                5063
#define IDB_GRID_DISABLED               5064
#define IDC_TD_RPM_GRID_BUTTON          5065
#define IDS_TD_RPM_GRID_BUTTON_TT       5066
#define IDC_TD_GME_IGN_CHECK            5067
#define IDD_GRID_MODE_EDITOR_IGN        5068
#define IDC_GME_IGN_WRK                 5069
#define IDC_GME_IGN_IDL                 5330
#define IDC_GME_IGN_TMP                 5346
#define IDC_GME_IGN_STR                 5362
#define IDC_GME_IDL_TITLE               5426
#define IDC_GME_TMP_TITLE               5427
#define IDC_GME_STR_TITLE               5428
#define IDC_GME_AA_CAPTION              5429
#define IDC_GME_WM_CAPTION              5430
#define IDC_GME_OC_CAPTION              5431
#define IDC_GME_TC_CAPTION              5432
#define IDC_GME_KC_CAPTION              5433
#define IDC_GME_IM_CAPTION              5434
#define IDC_GME_IC_CAPTION              5435
#define IDC_GME_AC_CAPTION              5436
#define IDC_GME_AA_VALUE                5437
#define IDC_GME_WM_VALUE                5438
#define IDC_GME_OC_VALUE                5439
#define IDC_GME_TC_VALUE                5440
#define IDC_GME_KC_VALUE                5441
#define IDC_GME_IM_VALUE                5442
#define IDC_GME_IC_VALUE                5443
#define IDC_GME_AC_VALUE                5444
#define IDC_GME_AAE_TEXT                5445
#define IDC_GME_WMP_TEXT                5446
#define IDC_GME_OCP_TEXT                5447
#define IDC_GME_TCP_TEXT                5448
#define IDC_GME_KCP_TEXT                5449
#define IDC_GME_IMP_TEXT                5450
#define IDC_GME_ICP_TEXT                5451
#define IDC_GME_AA_UNIT                 5452
#define IDI_GRAPH                       5453
#define IDC_TD_VIEW_VE_MAP              5454
#define IDC_TD_VIEW_AFR_MAP             5455
#define IDC_TD_VIEW_CRNK_MAP            5456
#define IDC_TD_VIEW_WRMP_MAP            5457
#define IDC_TD_VIEW_DEAD_MAP            5458
#define IDC_TD_VIEW_IDLR_MAP            5459
#define IDC_TD_VIEW_IDLC_MAP            5460
#define IDC_TD_VIEW_ATS_CURVE           5461
#define IDC_TD_VIEW_ATS_MAP             5462
#define IDS_ATS_CURVE_MAP               5463
#define IDS_ATSCORR_MAP                 5464
#define IDS_VE_MAP                      5465
#define IDS_MAPS_VE_UNIT                5466
#define IDS_MAPS_AFR_UNIT               5467
#define IDS_AFR_MAP                     5468
#define IDS_CRNK_MAP                    5469
#define IDS_MAPS_INJPW_UNIT             5470
#define IDS_MAPS_WRMP_UNIT              5471
#define IDS_WRMP_MAP                    5472
#define IDS_MAPS_DEAD_UNIT              5473
#define IDS_DEAD_MAP                    5474
#define IDS_MAPS_IAC_UNIT               5475
#define IDS_IDLR_MAP                    5476
#define IDS_IDLC_MAP                    5477
#define IDC_TD_VIEW_AETPS_MAP           5478
#define IDC_TD_VIEW_AERPM_MAP           5479
#define IDS_AETPS_MAP                   5480
#define IDS_MAPS_DPDT_UNIT              5481
#define IDS_MAPS_AETPS_UNIT             5482
#define IDS_AERPM_MAP                   5483
#define IDS_MAPS_AERPM_UNIT             5484
#define IDC_TD_VIEW_AFTSTR_MAP          5485
#define IDS_MAPS_AFTSTR_UNIT            5486
#define IDS_AFTSTR_MAP                  5487
#define IDC_TD_VIEW_GDP_MAP             5488
#define IDS_MAPS_GDP_UNIT               5489
#define IDC_TD_VIEW_IT_MAP              5490
#define IDS_MAPS_INJTIM_UNIT            5491
#define IDS_IT_MAP                      5492
#define IDS_GDP_MAP                     5493
#define IDC_TD_VIEW_ITRPM_MAP           5494
#define IDC_TD_VIEW_RIGID_MAP           5495
#define IDS_MAPS_COEFF_UNIT             5496
#define IDS_ITRPM_MAP                   5497
#define IDS_RIGID_MAP                   5498
#define IDC_TD_VIEW_EGOCRV_MAP          5499
#define IDS_EGO_CURVE_MAP               5500
#define IDS_MAPS_RIGID_UNIT             5501
#define IDC_TD_EDIT_CEPAR               5502
#define IDD_CESETTINGS_EDITOR           5503
#define IDC_CESETT_MAP_V_MIN_EDIT       5504
#define IDC_CESETT_MAP_V_MIN_SPIN       5505
#define IDC_CESETT_MAP_V_MAX_EDIT       5506
#define IDC_CESETT_MAP_V_MAX_SPIN       5507
#define IDC_CESETT_MAP_V_EM_EDIT        5508
#define IDC_CESETT_MAP_V_EM_SPIN        5509
#define IDC_CESETT_CTS_V_MIN_EDIT       5510
#define IDC_CESETT_CTS_V_MIN_SPIN       5511
#define IDC_CESETT_CTS_V_MAX_EDIT       5512
#define IDC_CESETT_CTS_V_MAX_SPIN       5513
#define IDC_CESETT_CTS_V_EM_EDIT        5514
#define IDC_CESETT_CTS_V_EM_SPIN        5515
#define IDC_CESETT_TPS_V_MIN_EDIT       5516
#define IDC_CESETT_TPS_V_MIN_SPIN       5517
#define IDC_CESETT_TPS_V_MAX_EDIT       5518
#define IDC_CESETT_TPS_V_MAX_SPIN       5519
#define IDC_CESETT_TPS_V_EM_EDIT        5520
#define IDC_CESETT_TPS_V_EM_SPIN        5521
#define IDC_CESETT_VBAT_V_MIN_EDIT      5522
#define IDC_CESETT_VBAT_V_MIN_SPIN      5523
#define IDC_CESETT_VBAT_V_MAX_EDIT      5524
#define IDC_CESETT_VBAT_V_MAX_SPIN      5525
#define IDC_CESETT_VBAT_V_EM_EDIT       5526
#define IDC_CESETT_VBAT_V_EM_SPIN       5527
#define IDC_CESETT_ADD_I1_V_MIN_EDIT    5528
#define IDC_CESETT_ADD_I1_V_MIN_SPIN    5529
#define IDC_CESETT_ADD_I1_V_MAX_EDIT    5530
#define IDC_CESETT_ADD_I1_V_MAX_SPIN    5531
#define IDC_CESETT_ADD_I1_V_EM_EDIT     5532
#define IDC_CESETT_ADD_I1_V_EM_SPIN     5533
#define IDC_CESETT_ADD_I2_V_MIN_EDIT    5534
#define IDC_CESETT_ADD_I2_V_MIN_SPIN    5535
#define IDC_CESETT_ADD_I2_V_MAX_EDIT    5536
#define IDC_CESETT_ADD_I2_V_MAX_SPIN    5537
#define IDC_CESETT_ADD_I2_V_EM_EDIT     5538
#define IDC_CESETT_ADD_I2_V_EM_SPIN     5539
#define IDC_CESETT_KS_V_MIN_EDIT        5540
#define IDC_CESETT_KS_V_MIN_SPIN        5541
#define IDC_CESETT_KS_V_MAX_EDIT        5542
#define IDC_CESETT_KS_V_MAX_SPIN        5543
#define IDC_CESETT_KS_V_EM_EDIT         5544
#define IDC_CESETT_KS_V_EM_SPIN         5545
#define IDC_TD_VIEW_IACC_MAP            5546
#define IDC_TD_VIEW_IACCW_MAP           5547
#define IDS_IACC_CURVE_MAP              5548
#define IDS_IACCW_CURVE_MAP             5549
#define IDS_MAPS_IACPOS_UNIT            5550
#define IDS_MAPS_TPSPOS_UNIT            5551
#define IDC_TD_VIEW_IATCLT_MAP          5552
#define IDS_IATCLT_CORR_MAP             5553
#define IDS_MAPS_AIRFLOW_UNIT           5554
#define IDC_CESETT_ADD_I3_V_MIN_EDIT    5555
#define IDC_CESETT_ADD_I3_V_MIN_SPIN    5556
#define IDC_CESETT_ADD_I3_V_MAX_EDIT    5557
#define IDC_CESETT_ADD_I3_V_MAX_SPIN    5558
#define IDC_CESETT_ADD_I3_V_EM_EDIT     5559
#define IDC_CESETT_ADD_I3_V_EM_SPIN     5560
#define IDC_CESETT_ADD_I4_V_MIN_EDIT    5561
#define IDC_CESETT_ADD_I4_V_MIN_SPIN    5562
#define IDC_CESETT_ADD_I4_V_MAX_EDIT    5563
#define IDC_CESETT_ADD_I4_V_MAX_SPIN    5564
#define IDC_CESETT_ADD_I4_V_EM_EDIT     5565
#define IDC_CESETT_ADD_I4_V_EM_SPIN     5566
#define IDC_CESETT_ADD_I3_GROUP         5567
#define IDC_CESETT_ADD_I3_V_MIN_CAPTION 5568
#define IDC_CESETT_ADD_I3_V_MAX_CAPTION 5569
#define IDC_CESETT_ADD_I3_V_EM_CAPTION  5570
#define IDC_CESETT_ADD_I4_GROUP         5571
#define IDC_CESETT_ADD_I4_V_MIN_CAPTION 5572
#define IDC_CESETT_ADD_I4_V_MAX_CAPTION 5573
#define IDC_CESETT_ADD_I4_V_EM_CAPTION  5574
#define IDC_TD_VIEW_BAROCORR_MAP        5575
#define IDS_BAROCORR_MAP                5576
#define IDS_MAPS_ATMOPRESS_UNIT         5577
#define IDS_MAPS_COEFFP_UNIT            5578
#define IDC_TD_VIEW_MANIGNTIM_MAP       5579
#define IDS_MANIGNTIM_MAP               5580
#define IDC_TD_VIEW_TPSSWT_MAP          5581
#define IDS_MAPS_TPSSWT_UNIT            5582
#define IDS_TPSSWT_MAP                  5583
#define IDC_TD_VIEW_TMP2_CURVE          5584
#define IDS_TMP2_CURVE_MAP              5585
#define IDC_TD_VIEW_GTSC_MAP            5586
#define IDC_TD_VIEW_GPSC_MAP            5587
#define IDS_GTSC_MAP                    5588
#define IDS_GPSC_MAP                    5589
#define IDS_MAPS_PRESS_UNIT             5590
#define IDC_TD_VIEW_ATSC_MAP            5591
#define IDS_ATSC_MAP                    5592
#define IDC_TD_VIEW_CRKTEMP_MAP         5593
#define IDS_CRKTEMP_MAP                 5594
#define IDC_CESETT_MAP_V_USEEM_CHECK    5595
#define IDC_CESETT_CTS_V_USEEM_CHECK    5596
#define IDC_CESETT_TPS_V_USEEM_CHECK    5597
#define IDC_CESETT_VBAT_V_USEEM_CHECK   5598
#define IDC_CESETT_ADD_I1_V_USEEM_CHECK 5599
#define IDC_CESETT_ADD_I2_V_USEEM_CHECK 5600
#define IDC_CESETT_ADD_I3_V_USEEM_CHECK 5601
#define IDC_CESETT_ADD_I4_V_USEEM_CHECK 5602
#define IDC_CESETT_KS_V_USEEM_CHECK     5603
#define IDC_TD_VIEW_EH_PAUSE_MAP        5604
#define IDS_MAPS_EH_PAUSE_UNIT          5605
#define IDS_EH_PAUSE_MAP                5606
#define IDC_TD_GME_INJ_CHECK            5607
#define IDD_GRID_MODE_EDITOR_INJ        5608
#define IDC_GME_INJ_TAB_CTRL            5609
#define IDD_GME_INJ_VE                  5610
#define IDS_GME_INJ_VE_TAB              5611
#define IDC_GME_INJ_VE                  5612
#define IDD_GME_INJ_AFR                 5613
#define IDS_GME_INJ_AFR_TAB             5614
#define IDC_GME_INJ_AFR                 5615
#define IDD_GME_INJ_IT                  5616
#define IDS_GME_INJ_IT_TAB              5617
#define IDC_GME_INJ_IT                  5618
#define IDD_GME_INJ_IREG                5619
#define IDS_GME_INJ_IREG_TAB            5620
#define IDC_GME_INJ_IDLC                5621
#define IDC_GME_INJ_IDLR                5622
#define IDC_GME_INJ_ITRPM               5623
#define IDC_GME_INJ_RIGID               5624
#define IDC_GME_INJ_IACC                5625
#define IDC_GME_INJ_IACCW               5626
#define IDD_GME_INJ_ENR                 5627
#define IDS_GME_INJ_ENR_TAB             5628
#define IDC_GME_INJ_AFTSTR              5629
#define IDC_GME_INJ_WRMP                5630
#define IDC_GME_INJ_AETPS               5631
#define IDC_GME_INJ_AERPM               5632
#define IDD_GME_INJ_OTHER               5633
#define IDS_GME_INJ_OTHER_TAB           5634
#define IDC_GME_INJ_CRNK                5635
#define IDC_GME_INJ_DEAD0               5636
#define IDC_GME_INJ_DEAD1               5637
#define IDC_GME_INJ_EGOCRV              5638
#define IDC_GME_INJ_IATCLT              5639
#define IDC_GME_INJ_ATSC                5640
#define IDC_GME_INJ_GTSC                5641
#define IDC_GME_INJ_GPSC                5642
#define IDC_GME_INJ_LAMDEL_BTN          5644
#define IDC_GME_INJ_CELWGT_BTN          5645
#define IDC_GME_INJ_STRSTP_BTN          5646
#define IDC_GME_INJ_RSTSTT_BTN          5647
#define IDC_GME_AUTOTUNE_GROUPBOX       5648
#define IDC_GME_INJ_LAMDEL_MAP          5649
#define IDC_GME_INJ_CELWGT_MAP          5650
#define IDC_GME_INJ_STATUS_TEXT         5651
#define IDS_GME_INJ_STATUS_INIFIFO      5652
#define IDS_GME_INJ_STATUS_STOP         5653
#define IDS_GME_INJ_BUTTON_STOP         5654
#define IDS_GME_INJ_BUTTON_START        5655
#define IDS_GME_INJ_STATUS_EGOCFG       5656
#define IDC_GME_INJ_CELBLK_BTN          5657
#define IDS_GME_INJ_CELBLK              5658
#define IDS_GME_INJ_CELUNBLK            5659
#define IDC_GME_INJ_SMOOTH_BTN          5660
#define IDC_GME_INJ_BLKALL_CHECK        5661
#define IDC_GME_INJ_FINISH_CHECK        5662
#define IDS_GME_INJ_STATUS_CLTTH        5663
#define IDC_GME_INJ_RSTALL_CHECK        5664
#define IDC_GME_IT_MODE_COMBO           5665
#define IDS_GME_IT_MODE_720BTDC         5666
#define IDS_GME_IT_MODE_720ATDC         5667
#define IDS_GME_IT_MODE_M360360         5668
#define IDS_GME_IT_MODE_M360360A        5669
#define IDS_MAPS_INJTIM_UNIT1           5670
#define IDB_CONST_UP                    5671
#define IDB_CONST_DOWN                  5672
#define IDB_CONST_FOCUSED               5673
#define IDB_CONST_DISABLED              5674
#define IDC_TD_FW_CONSTS_BUTTON         5675
#define IDC_TD_CRANKING_THRD_MAP        5676
#define IDC_TD_CRANKING_TIME_MAP        5677
#define IDC_TD_SMAPABAN_THRD_MAP        5678
#define IDS_CRANKING_THRD_MAP           5679
#define IDS_CRANKING_TIME_MAP           5680
#define IDS_SMAPABAN_THRD_MAP           5681
#define IDS_MAPS_STROKE_UNIT            5682
#define IDD_CESETTINGS_CONTAINER        5683
#define IDC_CGE_EDIT_0                  5684
#define IDC_CGE_EDIT_1                  5685
#define IDC_CGE_EDIT_2                  5686
#define IDC_CGE_EDIT_3                  5687
#define IDC_CGE_EDIT_4                  5688
#define IDC_CGE_EDIT_5                  5689
#define IDC_CGE_EDIT_6                  5690
#define IDC_CGE_EDIT_7                  5691
#define IDC_CGE_EDIT_8                  5692
#define IDC_CGE_EDIT_9                  5693
#define IDC_CGE_EDIT_10                 5694
#define IDC_CGE_EDIT_11                 5695
#define IDC_CGE_EDIT_12                 5696
#define IDC_CGE_EDIT_13                 5697
#define IDC_CGE_EDIT_14                 5698
#define IDC_CGE_EDIT_15                 5699
#define IDC_CGE_LOAD_DEF_VAL            5700
#define IDC_CGE_ERROR_MSG_TEXT          5701
#define IDS_TD_FW_CONSTS_BUTTON_TT      5702
#define IDS_TD_FUNSET_LIST_TT           5703
#define IDS_TD_GME_IGN_CHECK_TT         5704
#define IDS_TD_GME_INJ_CHECK_TT         5705
#define IDS_DWELL_CALC_R_EDIT_TT        5706
#define IDS_DWELL_CALC_L_EDIT_TT        5707
#define IDS_DWELL_CALC_I_EDIT_TT        5708
#define IDS_RGE_LOAD_DEF_VAL_TT         5709
#define IDS_CGE_LOAD_DEF_VAL_TT         5710
#define IDS_TD_VIEW_START_MAP_TT        5711
#define IDS_TD_VIEW_IDLE_MAP_TT         5712
#define IDS_TD_VIEW_WORK_MAP_TT         5713
#define IDS_TD_VIEW_TEMP_MAP_TT         5714
#define IDS_TD_VIEW_CRKTEMP_MAP_TT      5715
#define IDS_TD_VIEW_ATTENUATOR_MAP_TT   5716
#define IDS_TD_VIEW_CRNK_MAP_TT         5717
#define IDS_TD_VIEW_GDP_MAP_TT          5718
#define IDS_TD_VIEW_VE_MAP_TT           5719
#define IDS_TD_VIEW_AFR_MAP_TT          5720
#define IDS_TD_VIEW_WRMP_MAP_TT         5721
#define IDS_TD_VIEW_ATSC_MAP_TT         5722
#define IDS_TD_VIEW_AETPS_MAP_TT        5723
#define IDS_TD_VIEW_AERPM_MAP_TT        5724
#define IDS_TD_VIEW_AFTSTR_MAP_TT       5725
#define IDS_TD_VIEW_BAROCORR_MAP_TT     5726
#define IDS_TD_VIEW_GTSC_MAP_TT         5727
#define IDS_TD_VIEW_GPSC_MAP_TT         5728
#define IDS_TD_VIEW_DEAD_MAP_TT         5729
#define IDS_TD_VIEW_IDLR_MAP_TT         5730
#define IDS_TD_VIEW_IDLC_MAP_TT         5731
#define IDS_TD_VIEW_IT_MAP_TT           5732
#define IDS_TD_VIEW_ITRPM_MAP_TT        5733
#define IDS_TD_VIEW_RIGID_MAP_TT        5734
#define IDS_TD_VIEW_EGOCRV_MAP_TT       5735
#define IDS_TD_VIEW_IACC_MAP_TT         5736
#define IDS_TD_VIEW_IACCW_MAP_TT        5737
#define IDS_TD_VIEW_IATCLT_MAP_TT       5738
#define IDS_TD_VIEW_TPSSWT_MAP_TT       5739
#define IDS_TD_VIEW_CTS_CURVE_TT        5740
#define IDS_TD_VIEW_ATS_CURVE_TT        5741
#define IDS_TD_VIEW_ATS_MAP_TT          5742
#define IDS_TD_EDIT_CEPAR_TT            5743
#define IDS_TD_VIEW_MANIGNTIM_MAP_TT    5744
#define IDS_TD_VIEW_TMP2_CURVE_TT       5745
#define IDS_TD_VIEW_EH_PAUSE_MAP_TT     5746
#define IDS_TD_CRANKING_THRD_MAP_TT     5747
#define IDS_TD_CRANKING_TIME_MAP_TT     5748
#define IDS_TD_SMAPABAN_THRD_MAP_TT     5749
#define IDS_GME_IT_MODE_COMBO_TT        5750
#define IDS_GME_INJ_LAMDEL_BTN_TT       5751
#define IDS_GME_INJ_CELWGT_BTN_TT       5752
#define IDS_GME_INJ_STRSTP_BTN_TT       5753
#define IDS_GME_INJ_RSTSTT_BTN_TT       5754
#define IDS_GME_INJ_RSTALL_CHECK_TT     5755
#define IDS_GME_INJ_CELBLK_BTN_TT       5756
#define IDS_GME_INJ_BLKALL_CHECK_TT     5757
#define IDS_GME_INJ_SMOOTH_BTN_TT       5758
#define IDS_GME_INJ_FINISH_CHECK_TT     5759
#define IDC_GME_ACRONYMS_LINK           5760
#define IDC_CURSOR_HAND                 5761
#define IDS_GME_DESCR_ABBREV            5762
#define IDC_TD_VIEW_PWM1_MAP            5763
#define IDC_TD_VIEW_PWM2_MAP            5764
#define IDS_TD_VIEW_PWM1_MAP_TT         5765
#define IDS_TD_VIEW_PWM2_MAP_TT         5766
#define IDS_PWM1_MAP                    5767
#define IDS_PWM2_MAP                    5768
#define IDS_MAPS_DUTY_UNIT              5769
#define IDD_GME_INJ_PWM1                5770
#define IDD_GME_INJ_PWM2                5771
#define IDC_GME_INJ_PWM1                5772
#define IDC_GME_INJ_PWM2                5773
#define IDS_GME_INJ_PWM1_TAB            5774
#define IDS_GME_INJ_PWM2_TAB            5775
#define IDC_TD_KNOCK_ZONES_MAP          5776
#define IDS_MAPS_KNOCK_ZONE_UNIT        5777
#define IDS_KNOCK_ZONE_MAP              5778
#define IDS_TD_VIEW_KNOCK_ZONE_MAP_TT   5779
#define IDS_SPLIT_ANGLE_MAP             5780
#define IDS_TD_VIEW_PWM1_MAP            5781
#define IDS_TD_VIEW_SPLIT_MAP           5782
#define IDS_GME_INJ_SPLIT_TAB           5783
#define IDC_CESETT_ADD_I5_V_MIN_EDIT    5784
#define IDC_CESETT_ADD_I5_V_MIN_SPIN    5785
#define IDC_CESETT_ADD_I5_V_MAX_EDIT    5786
#define IDC_CESETT_ADD_I5_V_MAX_SPIN    5787
#define IDC_CESETT_ADD_I5_V_EM_EDIT     5788
#define IDC_CESETT_ADD_I5_V_EM_SPIN     5789
#define IDC_CESETT_ADD_I5_GROUP         5790
#define IDC_CESETT_ADD_I5_V_MIN_CAPTION 5791
#define IDC_CESETT_ADD_I5_V_MAX_CAPTION 5792
#define IDC_CESETT_ADD_I5_V_EM_CAPTION  5793
#define IDC_CESETT_ADD_I6_V_MIN_EDIT    5794
#define IDC_CESETT_ADD_I6_V_MIN_SPIN    5795
#define IDC_CESETT_ADD_I6_V_MAX_EDIT    5796
#define IDC_CESETT_ADD_I6_V_MAX_SPIN    5797
#define IDC_CESETT_ADD_I6_V_EM_EDIT     5798
#define IDC_CESETT_ADD_I6_V_EM_SPIN     5799
#define IDC_CESETT_ADD_I6_GROUP         5800
#define IDC_CESETT_ADD_I6_V_MIN_CAPTION 5801
#define IDC_CESETT_ADD_I6_V_MAX_CAPTION 5802
#define IDC_CESETT_ADD_I6_V_EM_CAPTION  5803
#define IDC_CESETT_ADD_I7_V_MIN_EDIT    5804
#define IDC_CESETT_ADD_I7_V_MIN_SPIN    5805
#define IDC_CESETT_ADD_I7_V_MAX_EDIT    5806
#define IDC_CESETT_ADD_I7_V_MAX_SPIN    5807
#define IDC_CESETT_ADD_I7_V_EM_EDIT     5808
#define IDC_CESETT_ADD_I7_V_EM_SPIN     5809
#define IDC_CESETT_ADD_I7_GROUP         5810
#define IDC_CESETT_ADD_I7_V_MIN_CAPTION 5811
#define IDC_CESETT_ADD_I7_V_MAX_CAPTION 5812
#define IDC_CESETT_ADD_I7_V_EM_CAPTION  5813
#define IDC_CESETT_ADD_I8_V_MIN_EDIT    5814
#define IDC_CESETT_ADD_I8_V_MIN_SPIN    5815
#define IDC_CESETT_ADD_I8_V_MAX_EDIT    5816
#define IDC_CESETT_ADD_I8_V_MAX_SPIN    5817
#define IDC_CESETT_ADD_I8_V_EM_EDIT     5818
#define IDC_CESETT_ADD_I8_V_EM_SPIN     5819
#define IDC_CESETT_ADD_I8_GROUP         5820
#define IDC_CESETT_ADD_I8_V_MIN_CAPTION 5821
#define IDC_CESETT_ADD_I8_V_MAX_CAPTION 5822
#define IDC_CESETT_ADD_I8_V_EM_CAPTION  5823
#define IDC_CESETT_ADD_I5_V_USEEM_CHECK 5824
#define IDC_CESETT_ADD_I6_V_USEEM_CHECK 5825
#define IDC_CESETT_ADD_I7_V_USEEM_CHECK 5826
#define IDC_CESETT_ADD_I8_V_USEEM_CHECK 5827
#define IDC_TD_GRTS_CURVE               5828
#define IDS_TD_GRTS_CURVE_TT            5829
#define IDS_GRTS_CURVE_MAP              5830 
#define IDS_GRHEAT_DUTY_MAP             5831
#define IDC_TD_GRHEAT_DUTY_MAP          5832
#define IDS_TD_GRHEAT_DUTY_MAP_TT       5833
#define IDC_TD_PWMIAC_UCOEF_MAP         5834
#define IDS_TD_PWMIAC_UCOEF_MAP_TT      5835
#define IDS_PWMIAC_UCOEF_MAP            5836
#define IDC_LGE_EDIT_0                  5837
#define IDC_LGE_EDIT_1                  5838
#define IDC_LGE_EDIT_2                  5839
#define IDC_LGE_EDIT_3                  5840
#define IDC_LGE_EDIT_4                  5841
#define IDC_LGE_EDIT_5                  5842
#define IDC_LGE_EDIT_6                  5843
#define IDC_LGE_EDIT_7                  5844
#define IDC_LGE_EDIT_8                  5845
#define IDC_LGE_EDIT_9                  5846
#define IDC_LGE_EDIT_10                 5847
#define IDC_LGE_EDIT_11                 5848
#define IDC_LGE_EDIT_12                 5849
#define IDC_LGE_EDIT_13                 5850
#define IDC_LGE_EDIT_14                 5851
#define IDC_LGE_EDIT_15                 5852
#define IDC_LGE_LOAD_DEF_VAL            5853
#define IDC_LGE_ERROR_MSG_TEXT          5854
#define IDS_LGE_LOAD_DEF_VAL_TT         5855
#define IDC_TD_AFTSTR_STRK0_MAP         5856
#define IDC_TD_AFTSTR_STRK1_MAP         5857
#define IDS_TD_AFTSTR_STRK0_MAP_TT      5858
#define IDS_TD_AFTSTR_STRK1_MAP_TT      5859
#define IDS_AFTSTR_STRK0_MAP            5860
#define IDS_AFTSTR_STRK1_MAP            5861
#define IDC_TD_VIEW_TEMPI_MAP           5862
#define IDS_TD_VIEW_TEMPI_MAP_TT        5863
#define IDS_TEMPCORRI_MAP               5864
#define IDC_GME_IGN_CLTSEL              5865
#define IDS_GME_IGN_CLTSEL_TT           5866
#define IDC_GME_IGN_TMPI                5867
#define IDC_TD_GRVDELAY_MAP             5868
#define IDS_MAPS_GRVDELAY_UNIT          5869
#define IDS_GRVDELAY_MAP                5870
#define IDS_TD_GRVDELAY_MAP_TT          5871
#define IDS_CESETT_MAP_V_MIN_EDIT_TT    5872
#define IDS_CESETT_MAP_V_MAX_EDIT_TT    5873
#define IDS_CESETT_MAP_V_EM_EDIT_TT     5874
#define IDS_CESETT_MAP_V_USEEM_CHECK_TT 5875
#define IDC_TD_VIEW_IACMAT_MAP          5876
#define IDS_TD_VIEW_IACMAT_MAP_TT       5877
#define IDC_GME_INJ_IACMAT              5878
#define IDS_MAPS_CORR_UNIT              5879
#define IDS_IACMAT_MAP                  5880
#define IDS_TD_VIEW_VE2_MAP_TT          5881
#define IDS_VE2_MAP                     5882
#define IDC_TD_VIEW_VE2_MAP             5883
#define IDC_GME_INJ_VE1_RADIOBOX        5884
#define IDC_GME_INJ_VE2_RADIOBOX        5885
#define IDS_GME_INJ_VE1_RADIOBOX_TT     5886
#define IDS_GME_INJ_VE2_RADIOBOX_TT     5887
#define IDC_GME_INJ_VE2                 5888
#define IDC_GME_INJ_IDLC_TEXT           5889
#define IDC_GME_INJ_IDLR_TEXT           5890
#define IDC_GME_INJ_ITRPM_TEXT          5891
#define IDC_GME_INJ_RIGID_TEXT          5892
#define IDC_GME_INJ_IACC_TEXT           5893
#define IDC_GME_INJ_IACCW_TEXT          5894
#define IDC_GME_INJ_IACMAT_TEXT         5895
#define IDC_GME_INJ_AFTSTR_TEXT         5896 
#define IDC_GME_INJ_WRMP_TEXT           5897
#define IDC_GME_INJ_AETPS_TEXT          5898
#define IDC_GME_INJ_AERPM_TEXT          5899
#define IDC_GME_INJ_AEMAP_TEXT          5900
#define IDC_GME_INJ_CRNK_TEXT           5901      
#define IDC_GME_INJ_DEAD_TEXT           5902
#define IDC_GME_INJ_EGOCRV_TEXT         5903
#define IDC_GME_INJ_IATCLT_TEXT         5904
#define IDC_GME_INJ_ATSC_TEXT           5905
#define IDC_GME_INJ_GTSC_TEXT           5906
#define IDC_GME_INJ_GPSC_TEXT           5907
#define IDC_TD_FTLS_CURVE               5908
#define IDC_TD_EGTS_CURVE               5909
#define IDC_TD_OPS_CURVE                5910
#define IDS_TD_FTLS_CURVE_TT            5911
#define IDS_TD_EGTS_CURVE_TT            5912
#define IDS_TD_OPS_CURVE_TT             5913
#define IDS_FTLS_CURVE_MAP              5914
#define IDS_EGTS_CURVE_MAP              5915
#define IDS_OPS_CURVE_MAP               5916
#define IDS_MAPS_FUELTANK_UNIT          5917
#define IDS_MAPS_PRESSUREKG_UNIT        5918
#define IDC_TD_MANINJPWC_MAP            5919
#define IDS_TD_MANINJPWC_MAP_TT         5920
#define IDS_MANINJPWC_MAP               5921
#define IDC_CESETT_OILPRESS_GROUP       5922
#define IDC_CESETT_OILPRESS_THRD_CAPTION 5923
#define IDC_CESETT_OILPRESS_THRD_EDIT   5924
#define IDC_CESETT_OILPRESS_THRD_SPIN   5925
#define IDC_CESETT_OILPRESS_TIMER_CAPTION 5926
#define IDC_CESETT_OILPRESS_TIMER_EDIT  5927
#define IDC_CESETT_OILPRESS_TIMER_SPIN  5928
#define IDS_CESETT_OILPRESS_THRD_EDIT_TT 5929
#define IDS_CESETT_OILPRESS_TIMER_EDIT_TT 5930
#define IDC_TD_MAF_CURVE                5931
#define IDS_TD_MAF_CURVE_TT             5932
#define IDS_MAF_CURVE_MAP               5933
#define IDS_MAF_UNIT                    5934
#define IDC_TD_VIEW_TPSZON_MAP          5935
#define IDS_TD_VIEW_TPSZON_MAP_TT       5936
#define IDS_TPSZON_MAP                  5937
#define IDS_MAPS_TPSZON_UNIT            5938
#define IDD_GME_INJ_OTHER1              5939
#define IDC_GME_INJ_TPSSWT_TEXT         5940
#define IDC_GME_INJ_TPSZON_TEXT         5941
#define IDC_GME_INJ_CYLMULT_TEXT        5942
#define IDC_GME_INJ_CYLADD_TEXT         5943
#define IDC_GME_INJ_THRASS_TEXT         5944
#define IDC_GME_INJ_TPSSWT              5945
#define IDC_GME_INJ_TPSZON              5946
#define IDS_GME_INJ_OTHER1_TAB          5947
#define IDS_GME_WM_CAPTION_WRKTEXT      5948
#define IDS_GME_WM_CAPTION_STRTEXT      5949
#define IDC_TD_FTLSCOR_MAP              5950
#define IDS_TD_FTLSCOR_MAP_TT           5951
#define IDS_FTLSCOR_MAP                 5952
#define IDC_TD_LAMBDA_ZONES_MAP         5953
#define IDS_TD_LAMBDA_ZONES_MAP_TT      5954
#define IDS_MAPS_LAMBDA_ZONE_UNIT       5955
#define IDS_LAMBDA_ZONE_MAP             5956
#define IDC_TD_VIEW_CYLMULT_MAP         5957
#define IDC_TD_VIEW_CYLADD_MAP          5958
#define IDS_TD_VIEW_CYLMULT_MAP_TT      5959
#define IDS_TD_VIEW_CYLADD_MAP_TT       5960
#define IDS_MAPS_CYLADD_UNIT            5961
#define IDS_MAPS_CYLADDY_UNIT           5962
#define IDS_INJ_CYLMULT_MAP             5963
#define IDS_INJ_CYLADD_MAP              5964
#define IDC_GME_INJ_CYLMULT             5965
#define IDC_GME_INJ_CYLADD              5966
#define IDC_GME_INJ_THRASS              5967
#define IDC_TD_VIEW_AEMAP_MAP           5968
#define IDS_TD_VIEW_AEMAP_MAP_TT        5969
#define IDS_MAPS_DPRDT_UNIT             5970
#define IDS_MAPS_AEMAP_UNIT             5971
#define IDS_AEMAP_MAP                   5972
#define IDC_GME_INJ_AEMAP               5973
#define IDC_TD_VIEW_THRASS_MAP          5974
#define IDS_THRASS_MAP                  5975
#define IDS_TD_VIEW_THRASS_MAP_TT       5976
#define IDC_TD_FTS_CURVE                5977
#define IDS_FTS_CURVE_MAP               5978
#define IDS_TD_FTS_CURVE_TT             5979
